test-suite: Factor counting results out of do_test()
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

diff --git a/tests/test-suite b/tests/test-suite
--- a/tests/test-suite
+++ b/tests/test-suite
@@ -151,34 +151,35 @@ do_test()
 			error "actual $stream text does not match expected $stream text."
 			error  "see $file.$stream.* for further investigation."
 			cat "$file".$stream.diff
-			test_failed=1
+			return 1
 		fi
 	done
 
 	if [ "$actual_exit_value" -ne "$expected_exit_value" ]; then
 		error "Actual exit value does not match the expected one."
 		error "expected $expected_exit_value, got $actual_exit_value."
-		test_failed=1
+		return 1
 	fi
 
-	if [ "$test_failed" -eq "1" ]; then
-		ko_tests=`expr $ko_tests + 1`
-		get_tag "check-known-to-fail" $file
-		if [ "$?" -eq "0" ]; then
-			echo "info: test '$file' is known to fail"
-			known_ko_tests=`expr $known_ko_tests + 1`
-		fi
-		return 1
-	else
-		ok_tests=`expr $ok_tests + 1`
-		return 0
-	fi
+	return 0
 }
 
 do_test_suite()
 {
 	for i in $tests_list; do
 		do_test "$i"
+		ret=$?
+
+		if [ "$ret" -eq "1" ]; then
+			ko_tests=`expr $ko_tests + 1`
+			get_tag "check-known-to-fail" $file
+			if [ "$?" -eq "0" ]; then
+				echo "info: test '$file' is known to fail"
+				known_ko_tests=`expr $known_ko_tests + 1`
+			fi
+		elif [ "$ret" -eq "0" ]; then
+			ok_tests=`expr $ok_tests + 1`
+		fi
 	done
 
 	# prints some numbers
