test-suite: Exit with a non 0 value on error
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

diff --git a/tests/test-suite b/tests/test-suite
--- a/tests/test-suite
+++ b/tests/test-suite
@@ -208,6 +208,11 @@ do_test_suite()
 	if [ "$disabled_tests" -ne "0" ]; then
 		echo "$disabled_tests tests were disabled"
 	fi
+
+	if [ "$ko_tests" -ne "0" ]; then
+		return 1
+	fi
+	return 0
 }
 
 ##
@@ -265,23 +270,26 @@ arg_file()
 	return 0
 }
 
+ret=0
 case "$1" in
 	'')
 		do_test_suite
+		ret=$?
 		;;
 	single)
 		arg_file "$2"
 		do_test "$2"
 		case "$?" in
 			0) echo "$2 passed!";;
-			1) echo "$2 failed!";;
-			2) echo "$2 can't be handled by $prog_name";;
+			1) echo "$2 failed!"; ret=1;;
+			2) echo "$2 can't be handled by $prog_name"; ret=1;;
 			3) echo "$2 is disabled";;
 		esac
 		;;
 	format)
 		arg_file "$2"
 		do_format "$2" "$3" "$4"
+		ret=$?
 		;;
 	help | *)
 		do_usage
@@ -289,5 +297,5 @@ case "$1" in
 		;;
 esac
 
-exit 0
+exit $ret
 
